export const metadata = {
    title: "TECHEASE || Blog-Avantages React et stack MERN",
    description: "Generated by create next app",
  };

export default function AdvantagesLayout({ children }) {
    return <section>{children}</section>
  }