export const metadata = {
    title: "TECHEASE || Présentation",
    description: "Generated by create next app",
  };

export default function AboutLayout({ children }) {
    return <section>{children}</section>
  }