export const metadata = {
    title: "TECHEASE || Mes services",
    description: "Generated by create next app",
  };

export default function ProjectDetailsLayout({ children }) {
    return <section>{children}</section>
  }