export const metadata = {
    title: "TECHEASE || Mes réalisations",
    description: "Generated by create next app",
  };

export default function ProjectLayout({ children }) {
    return <section>{children}</section>
  }