export const metadata = {
    title: "Project Details || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function ProjectDetailsLayout({ children }) {
    return <section>{children}</section>
  }