export const metadata = {
    title: "Contact || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function ContactLayout({ children }) {
    return <section>{children}</section>
  }