export const metadata = {
  title: "Testimonial || Pucu - Nextjs Portfolio Template",
  description: "Generated by create next app",
};

export default function TestimonialLayout({ children }) {
  return <section>{children}</section>;
}
