export const metadata = {
    title: "Blog || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function BlogLayout({ children }) {
    return <section>{children}</section>
  }