export const metadata = {
    title: "Blog Details || Pucu - Nextjs Portfolio Template",
    description: "Generated by create next app",
  };

export default function BlogDetailsLayout({ children }) {
    return <section>{children}</section>
  }